// lib/electionData.ts
// Static election knowledge base — timelines, FAQs, voting steps, documents

export const ELECTION_TIMELINE = [
  {
    id: 1,
    date: 'Oct 2024',
    title: 'Voter Roll Revision',
    description: 'Annual voter roll revision begins. Check and update your details.',
    status: 'completed',
    icon: '📋',
    color: 'bg-green-500',
  },
  {
    id: 2,
    date: 'Nov 2024',
    title: 'New Registration Deadline',
    description: 'Last date to submit Form 6 for new voter registration.',
    status: 'completed',
    icon: '📝',
    color: 'bg-green-500',
  },
  {
    id: 3,
    date: 'Dec 2024',
    title: 'Final Voter List Published',
    description: 'Final electoral rolls published. Verify your name at voterportal.eci.gov.in',
    status: 'current',
    icon: '📢',
    color: 'bg-blue-500',
  },
  {
    id: 4,
    date: 'Jan 2025',
    title: 'Election Schedule Announced',
    description: 'Election Commission announces official election dates and model code of conduct.',
    status: 'upcoming',
    icon: '📅',
    color: 'bg-gray-300',
  },
  {
    id: 5,
    date: 'Feb 2025',
    title: 'Nomination Filing',
    description: 'Candidates file nominations. Last date for withdrawal.',
    status: 'upcoming',
    icon: '🏛️',
    color: 'bg-gray-300',
  },
  {
    id: 6,
    date: 'Mar 2025',
    title: 'Election Day',
    description: 'Polling day. Vote at your designated polling booth. Bring your Voter ID.',
    status: 'upcoming',
    icon: '🗳️',
    color: 'bg-gray-300',
  },
  {
    id: 7,
    date: 'Mar 2025',
    title: 'Vote Counting',
    description: 'Votes counted under strict security. Results announced the same day.',
    status: 'upcoming',
    icon: '🔢',
    color: 'bg-gray-300',
  },
  {
    id: 8,
    date: 'Apr 2025',
    title: 'Results & Government Formation',
    description: 'Official results certified. New government formation begins.',
    status: 'upcoming',
    icon: '🏆',
    color: 'bg-gray-300',
  },
];

export const VOTING_STEPS = [
  {
    step: 1,
    title: 'Register to Vote',
    description: 'Fill Form 6 online at voterportal.eci.gov.in or visit your local BLO.',
    details: [
      'Visit voterportal.eci.gov.in',
      'Click "New Registration" → Fill Form 6',
      'Upload documents: Photo, Age proof, Address proof',
      'Submit and note your reference number',
      'Track status online within 30 days',
    ],
    icon: '📝',
    color: 'from-blue-500 to-blue-600',
  },
  {
    step: 2,
    title: 'Verify Your Voter ID',
    description: 'Ensure your Voter ID (EPIC) details are correct and up to date.',
    details: [
      'Check name spelling and address on EPIC card',
      'Verify constituency details at electoralsearch.eci.gov.in',
      'Update errors using Form 8',
      'Download e-EPIC (digital voter ID) from NVSP portal',
      'Keep original EPIC safe for election day',
    ],
    icon: '✅',
    color: 'from-purple-500 to-purple-600',
  },
  {
    step: 3,
    title: 'Find Your Polling Booth',
    description: 'Locate your designated polling station using your voter ID or address.',
    details: [
      'Visit electoralsearch.eci.gov.in',
      'Enter your Voter ID number or name/address',
      'Note your booth number and address',
      'Plan your route in advance',
      'Check booth timing (usually 7 AM – 6 PM)',
    ],
    icon: '📍',
    color: 'from-green-500 to-green-600',
  },
  {
    step: 4,
    title: 'Cast Your Vote',
    description: 'Visit your polling booth on election day and exercise your franchise.',
    details: [
      'Arrive early to avoid queues',
      'Carry your Voter ID (or accepted alternative ID)',
      'Show ID to polling officer and get inked finger',
      'Enter voting compartment — select candidate on EVM',
      'Press VVPAT slot confirmation, exit quietly',
    ],
    icon: '🗳️',
    color: 'from-orange-500 to-orange-600',
  },
];

export const FAQS = [
  {
    id: 'faq-1',
    category: 'Eligibility',
    question: 'Who is eligible to vote in India?',
    answer: 'Any Indian citizen who is 18 years or older and is ordinarily resident of their constituency is eligible to vote. NRIs can also register under special provisions.',
    tags: ['eligibility', 'age', 'citizenship'],
  },
  {
    id: 'faq-2',
    category: 'Registration',
    question: 'How do I register as a voter?',
    answer: 'Visit voterportal.eci.gov.in, click on "New Voter Registration" and fill Form 6. Alternatively, visit your local Electoral Registration Officer (ERO) or Booth Level Officer (BLO).',
    tags: ['registration', 'form 6', 'online'],
  },
  {
    id: 'faq-3',
    category: 'Documents',
    question: 'What documents do I need to register?',
    answer: 'You need: (1) Proof of Age – Birth certificate, 10th mark sheet, or Aadhaar; (2) Proof of Address – Aadhaar, Utility bill, or Bank passbook; (3) Recent passport-size photograph.',
    tags: ['documents', 'aadhaar', 'age proof'],
  },
  {
    id: 'faq-4',
    category: 'Voting',
    question: 'What should I carry to the polling booth?',
    answer: 'Carry your EPIC (Voter ID card). If unavailable, you can use 12 alternative documents including Aadhaar, PAN card, Passport, Driving license, or Bank passbook with photograph.',
    tags: ['polling booth', 'voter id', 'epic'],
  },
  {
    id: 'faq-5',
    category: 'Registration',
    question: 'What is the deadline for voter registration?',
    answer: 'There are 4 qualifying dates in a year: January 1, April 1, July 1, and October 1. Registration applications must be submitted before the revision schedule announced by ECI.',
    tags: ['deadline', 'registration', 'qualifying date'],
  },
  {
    id: 'faq-6',
    category: 'Voting',
    question: 'Can I vote if my name is not on the electoral roll?',
    answer: "No, you cannot vote if your name is not in the electoral roll of that constituency. Please check at electoralsearch.eci.gov.in and contact the ERO if there's an error.",
    tags: ['electoral roll', 'voter list', 'not registered'],
  },
  {
    id: 'faq-7',
    category: 'Booth',
    question: 'How do I find my polling booth?',
    answer: 'Visit electoralsearch.eci.gov.in and search by your name/EPIC number, or use the Voter Helpline app. Your polling station details are printed on your EPIC card and voter slip.',
    tags: ['polling booth', 'find booth', 'voter helpline'],
  },
  {
    id: 'faq-8',
    category: 'Process',
    question: 'What is EVM and how does it work?',
    answer: 'Electronic Voting Machine (EVM) is a standalone, tamper-proof device used to record votes electronically. Press the blue button next to your candidate. A VVPAT slip shows your vote for 7 seconds for verification.',
    tags: ['evm', 'electronic voting', 'vvpat'],
  },
  {
    id: 'faq-9',
    category: 'Eligibility',
    question: 'Can NRIs vote in Indian elections?',
    answer: "Non-Resident Indians (NRIs) can register as overseas voters under Section 20A of the Representation of the People Act using Form 6A. They must be present at their constituency's polling booth to vote.",
    tags: ['nri', 'overseas voter', 'abroad'],
  },
  {
    id: 'faq-10',
    category: 'Process',
    question: 'What is Model Code of Conduct?',
    answer: 'The Model Code of Conduct (MCC) is a set of guidelines issued by ECI for political parties and candidates during elections. It aims to ensure free and fair elections and comes into effect from the date of election announcement.',
    tags: ['mcc', 'code of conduct', 'guidelines'],
  },
];

export const VALID_DOCUMENTS = [
  { id: 'aadhaar', name: 'Aadhaar Card', categories: ['identity', 'address', 'age'], icon: '🪪' },
  { id: 'pan', name: 'PAN Card', categories: ['identity'], icon: '💳' },
  { id: 'passport', name: 'Passport', categories: ['identity', 'address', 'age'], icon: '📘' },
  { id: 'driving-license', name: 'Driving License', categories: ['identity', 'address'], icon: '🚗' },
  { id: 'voter-id', name: 'Voter ID (EPIC)', categories: ['identity', 'address'], icon: '🗳️' },
  { id: 'birth-certificate', name: 'Birth Certificate', categories: ['age'], icon: '📜' },
  { id: 'bank-passbook', name: 'Bank Passbook', categories: ['identity', 'address'], icon: '🏦' },
  { id: 'utility-bill', name: 'Utility Bill (< 3 months)', categories: ['address'], icon: '📄' },
  { id: '10th-marksheet', name: '10th Mark Sheet', categories: ['age', 'identity'], icon: '📚' },
  { id: 'caste-certificate', name: 'Caste Certificate (SC/ST)', categories: ['identity'], icon: '📋' },
];

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Chandigarh', 'Puducherry',
];

export const POLLING_CENTERS = [
  { id: 'pc1', name: 'Government School No. 1, Sector 21', city: 'Delhi', pincode: '110001', lat: 28.6139, lng: 77.2090, boothNo: 'B-101' },
  { id: 'pc2', name: 'Municipal Corporation Hall', city: 'Delhi', pincode: '110002', lat: 28.6200, lng: 77.2150, boothNo: 'B-102' },
  { id: 'pc3', name: 'Community Centre, Lajpat Nagar', city: 'Delhi', pincode: '110024', lat: 28.5677, lng: 77.2365, boothNo: 'B-203' },
  { id: 'pc4', name: 'Public Library, Connaught Place', city: 'Delhi', pincode: '110001', lat: 28.6315, lng: 77.2167, boothNo: 'B-010' },
  { id: 'pc5', name: 'Senior Secondary School, Rohini', city: 'Delhi', pincode: '110085', lat: 28.7354, lng: 77.1151, boothNo: 'B-445' },
  { id: 'pc6', name: 'Corporation Primary School, Bandra', city: 'Mumbai', pincode: '400050', lat: 19.0544, lng: 72.8406, boothNo: 'B-301' },
  { id: 'pc7', name: 'Municipal School, Andheri East', city: 'Mumbai', pincode: '400069', lat: 19.1136, lng: 72.8697, boothNo: 'B-302' },
  { id: 'pc8', name: 'Govt. High School, Shivajinagar', city: 'Bengaluru', pincode: '560001', lat: 12.9716, lng: 77.5946, boothNo: 'B-201' },
  { id: 'pc9', name: 'Community Hall, Koramangala', city: 'Bengaluru', pincode: '560034', lat: 12.9352, lng: 77.6245, boothNo: 'B-202' },
  { id: 'pc10', name: 'Govt. School, Anna Nagar', city: 'Chennai', pincode: '600040', lat: 13.0827, lng: 80.2707, boothNo: 'B-151' },
];
